<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create New CC Scenario</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>371f4a64-bb55-401a-996b-e9b8b84737a0</testSuiteGuid>
   <testCaseLink>
      <guid>778edde4-9b2a-4b2a-a18d-c1f75fadae62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Users Functionality/CC/createNewUser_DuplicatePhoneNumber</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8bef317-0f30-436b-88d3-133bbcdcbd12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1ce4568-8163-4d80-8396-c45a7f14f10c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d909a74f-3966-47fa-8ea9-6902a921edde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e41a2fb-d432-4fe6-8f08-c9be0f17de7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9109dfb3-277b-4384-a0e7-15127958e300</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce67e083-a07d-49e5-99ba-5cce6e5eab6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>965f165d-414f-47bb-b36b-7f00a00cfa76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Users Functionality/CC/createNewUser_DuplicateStaffNumber</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c8d9d4-39bc-4377-829d-e82e1461f6d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd383e4a-c84f-4f7d-a3a4-168ee625d4ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c66fe0ad-c974-4b44-b6eb-ea44dcf5d835</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0e1779a-a0c1-4af7-a1d0-1922dd7c9179</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d65854a1-25b1-455b-aeb1-5c101e17756a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d4bc724-fca4-4c58-93ea-905bd5a324a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9531d79-3842-49c2-a6f0-0289dc4a25a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Users Functionality/CC/createNewUser_Validation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7e53e68b-7305-4a36-a1b6-8b559ebdad51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Users Functionality/CC/createNewUser_DuplicateEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6708c17c-731f-40d0-a27a-03f444372024</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8763873-8fe0-4400-b2ae-89f729a382a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e08d8c9d-bda9-48c2-84c6-565c0f511c2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef89ac6-d299-4246-8392-fe9577a2a978</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c743736d-fa75-48e7-8796-557c773f85bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2eb487c-7f92-47f0-9ed5-2b33920e0ae3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
