<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Scenario Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6a04ecba-9480-46a4-9c62-25920239226b</testSuiteGuid>
   <testCaseLink>
      <guid>a475e6da-a482-4326-83a1-2054d1284689</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Scenarios/User_Login_EmailRequired</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7be13a1c-114e-4dac-8f75-9a8fbf7860d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143aad07-8194-4fc0-9e64-83924afcca5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce128d50-0b20-4fcc-96d5-9d24f7b352a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc6c10a0-357b-4d85-a20a-2a9695ddda67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Scenarios/User_Login_InvalidEmailPassword</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39535d8f-e2ed-476e-981d-1ae4994175f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>124b0f5f-44a0-4356-8dc6-5cdcd213dd99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>342ea727-af3a-4102-8cce-47343aeede8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4536873-a200-411a-aa65-9245abae35ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Scenarios/User_Login_PasswordRequired</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>492b1967-04c8-4e7d-8076-d7d447677756</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9717f50-4c09-4c7f-a807-51224b5deaa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f669032-f656-4cb1-bb67-4d1150602c10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>107a977f-7fce-4dc5-8fcb-9f453ae59fb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Scenarios/User_Login_UserNotFound</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d855c96-67ca-442e-bf14-af0c0b946e0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>567046b8-9b6f-4572-a2d1-ec5852d0f956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96950edb-e882-413e-8e60-d83b6a359592</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c1bbc58-d2d3-48e0-801c-be0d120be07d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Scenarios/User_Login_Correct_Credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf969dd6-9457-4eea-8c98-cbb333faaaee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a2b80b4-ff51-4618-ae9c-5f98d5e74617</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9319730-6629-4827-a6f2-549e855a5e54</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
